- docs/playbook/using-glue-studio.md
Co-authored-by: Emma Corbett <emma@madetech.com>
> Clarify we don't want to set the "Server-side encryption option"

- docs/playbook/import-xlsx-from-g-drive.md
> Suggested changes to the XLSX ingestion section

- docs/spikes/0007-datahub-deployment.md
- sidebars.js
Co-authored-by: el <elena@madetech.com>
This pr contains the outcomes for the Datahub tech spike
Added spikes to `sidebar.js`
> Add Datahub spike outcome

- docs/architecture-decisions/0010-using-pytest-for-verifying-pyspark-transformations.md
> Add ADR for "Using pytest for verifying PySpark transformations"

- docs/spikes/0008-amundsen-deployment.md
This pr includes the outcome of the Amundsen tech spike
> Amunsen tech spike documentation

- docs/playbook/unit-testing-guide.md
- Update guide to unit testing documentation to describe how testing fits into the CI/CD pipeline of the Data Platform project
> update unit testing guide on running tests as part of workflow

- docs/playbook/unit-testing-guide.md
- made improvements to the guide to unit testing from feedback from user testing session
> Update unit testing guide with feedback from unit testing user testing

- docs/playbook/unit-testing-guide.md
Taken while AG was teaching DC how to write tests
> Additions for a more step-by-step approach

- README.md
- Add explanation and guidance on how to deploy changes to the `README`
> Add information on automatic deploys via Actions

- docs/playbook/using-glue-studio.md
> Updated using-glue-studio with details about unrestricted department

- docs/playbook/transforming-data/create-glue-jobs.md
Note: this will be updated once changes to scripts folder structure are adding to the main project
> add instructions for adding scripts to the data platform repo

- docs/playbook/transforming-data/guides-to-testing-in-the-platform/004-unit-testing-guide.md
- Outlines where test files should now be saves
- Also add in guidance on how to add requirements
> Changes to testing based on the restructure of the scripts folder

- .gitmessage
- docs/playbook/transforming-data/using-aws-glue/002-deploy-glue-jobs.md
> Document the variables helper_module_key & pydeequ_zip_key

- docs/playbook/transforming-data/using-aws-glue/002-deploy-glue-jobs.md
- Add source to list of required variables
- Expand on job parameters to specifically mention job bookmarking
> A couple updates to the Glue job module

- docs/playbook/transforming-data/using-aws-glue/002-deploy-glue-jobs.md
- this is to reflect the change to the glue module where a list of s3 paths to extra jars can be passed in to a glue job
> update docs to include extra jars optional variable

- docs/playbook/getting-set-up/index.md
- docs/playbook/getting-set-up/using-github.md
- docs/playbook/ingesting-data/001-google-sheets-import.md
- docs/playbook/ingesting-data/003-ingest-xlsx-files-from-g-drive.md
- docs/playbook/ingesting-data/004-ingesting-rds-snapshot-in-landing-zone.md
- docs/playbook/transforming-data/guides-to-testing-in-the-platform/003-data-quality-testing-guide.md
- docs/playbook/transforming-data/using-aws-glue/001-using-glue-studio.md
- docs/playbook/transforming-data/using-aws-glue/002-deploy-glue-jobs.md
- contains a section on committing changes to the Data Platform Project
- all pages that require changes to be committed to the project now link to this new page
> Add `using GitHub` page under `Getting set up on the platform` directory

- docs/playbook/transforming-data/guides-to-testing-in-the-platform/003-data-quality-testing-guide.md
including:
- adding metrics repository information to script
- remembering to import checks, analyzer functions used
> Added some additional notes

- docs/playbook/transforming-data/using-aws-glue/001-using-glue-studio.md
Included documentation on pushdown predicates to the using glue studio guide
> Add documentation on adding pushdown predicates to jobs in glue studio

- docs/playbook/getting-set-up/onboarding-new-departments-to-the-platform.md
> Add a step to contact ask devops when creating a department

- docs/playbook/getting-set-up/onboarding-new-departments-to-the-platform.md
- docs/playbook/ingesting-data/001-google-sheets-import.md
Add instruction when creating a new department to do this in the future
> Add new departments to table on google sheets ingestion

- docs/Glossary.md
> Reformat Glossary to Header+Body

- docs/Glossary.md
> Updating links in Glossary

- docs/playbook/ingesting-data/005-database-ingestion.md
- Add documentation on how to ingest database data onto the Data Platform via jdbc connections
> Jdbc database ingestion

- docs/playbook/getting-set-up/onboarding-new-departments-to-the-platform.md
> Fix ICT support link

- docs/architecture-decisions/records/008-production-data-in-staging.md
- docs/architecture-decisions/records/012-do-not-connect-to-production-databases.md
- docs/architecture-decisions/records/012-move-staging-to-pre-production.md
- docs/architecture-decisions/records/014-using-event-streaming-to-ingest-data.md
- docs/architecture-decisions/records/015-initial-extract-of-tenure-data.md
The ADRs coving a range of topics up to Event Streaming and initial Extraction of the Tenure Data.
> Added various missing ADRs

- docs/playbook/Module-0.md
> Updated Tags in Module0

- docs/playbook/training-modules/Module-0.md
- sidebars.js
- Update Module 0 with grammar fixes and reformatting of links
- Update the sidebars.js file to display the Training Modules in the directory
> Update module 0

- docs/playbook/training-modules/Module-0.md
> Update Module-0 removed accordians

- docs/playbook/training-modules/Module-0.md
https://lbhackney-it.github.io/Data-Platform-Playbook/playbook/getting-set-up/notebook-setup instead of Google Docs
> Update the Notebook Environment Link

- docs/glossary.md
> add Terraform to Glossary

- docs/glossary.md
reverts the merge that should have been to main
> Revert 147 annajgibson patch 1

- src/docs.scss
Previous PR: https://github.com/LBHackney-IT/Data-Platform-Playbook/pull/151
> Same fix as before but the css class names have a hash in production so need to use attribute selector instead so it works in dev and deployed

- docs/playbook/training-modules/Module-01.md
> Changed title so that it reflects what module 1 covers.

- docs/playbook/ingesting-data/007-event-streaming.md
Explains how to add a schema for a new data type and a connector to consume messages from a topic
> Document how to setup new topics for event streaming

- docs/playbook/transforming-data/using-aws-glue/001-using-glue-studio.md
- docs/playbook/transforming-data/using-aws-glue/006-using-sagemaker.md
- docs/training-modules/module-1.md
- docs/training-modules/module-2.md
> Add improvements to documentation following module 2 training session

- docs/playbook/ingesting-data/005-database-ingestion.md
> Improvements to ingesting database data via jdbc connection documentation

- docs/training-modules/module-1.md
> Fix Module 0 link

- docs/playbook/ingesting-data/003-ingest-spreadsheet-files-from-g-drive.md
> Improve documentation on ingesting spreadsheets

- docs/playbook/ingesting-data/003-ingest-spreadsheet-files-from-g-drive.md
- docusaurus.config.js
- Adds a point to say when one should expect the data to be available in the Data Platform
- Prevents trailing slashes from being appended to URLs as in some instances this causes broken links
> Update spreadsheet ingestion

- sidebars.js
> Add Qlik Training modules to the sidebar

- docs/training-modules/Qlik/qlik-module-2.md
> New training module (02) for Qlik - developing a simple dashboard

- docs/training-modules/module-0.md
- docs/training-modules/module-3.md
> Changed module 0 intro paragraph. Amended module 3 title.

- docs/playbook/ingesting-data/009-ingesting-api-data.md
> Add documentation on ingesting api data via api ingestion lambda module

- docs/playbook/ingesting-data/003-manual-ingest-of-csv-files.md
> Update the manual CSV upload documentation to match the code

- docs/archived-articles/import-files-from-google-to-S3.md
- docs/playbook/ingesting-data/004-ingest-spreadsheet-files-from-g-drive.md
> Parking documentation updates

- docs/playbook/transforming-data/using-aws-glue/002-deploy-glue-jobs.md
> DPP-174 - Playbook update

- docs/playbook/querying-and-analysing-data/connecting-to-redshift-from-data-studio.md
Adds details for connecting to either Prod or Pre-prod
> Dpp 223 redshift docs

- docs/playbook/querying-and-analysing-data/connecting-to-redshift-from-data-studio.md
> Minor clarifications and new screenshot

- docs/docs/backdated-liberator-ingestion.md
> Backdated liberator ingestion

- docs/zones.md
I've had a go at updating the zone definitions following the colab exercise we completed. Feedback and/or edits much appreciated!
> DPP-253 update zones docs

- docs/playbook/ingesting-data/002-google-sheets-import.md
1. Fix file location path
2. Add warning that the worksheet name must be unique
> Google sheet instructions update

- docs/docs/alloy-ingestion.md
> close line break tags

- docs/architecture-decisions/records/013-using-event-streaming-to-ingest-data.md
> fix link to ADR 012

- docs/playbook/ingesting-data/009-ingesting-api-data.md
Add instructions how to include API ingestion Lambda to central alarms setup.
> Update api ingestion details with alerts information

- docs/environments.md
[DPP-254](https://hackney.atlassian.net/browse/DPP-254?atlOrigin=eyJpIjoiYjdhOTNmZDE4ZmJjNGFhYWEyZDQ4ZWU0MGE2MDMwYzQiLCJwIjoiaiJ9) 
Expands and updates on the environment definitions. 
[DPP-254]: https://hackney.atlassian.net/browse/DPP-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update environment definitions

- docs/docs/liberator-ingestion.md
Update the documentation to reflect the current setup. Also add some developer notes to help running the ingestion process in development environment.
> Update liberator ingestion documentation

- docs/playbook/ingesting-data/006-database-ingestion.md
- docs/playbook/ingesting-data/007-ingesting-dynamo-db-tables.md
- docs/playbook/transforming-data/using-aws-glue/002-deploy-glue-jobs.md
Update `crawler_details` to match the current configuration requirements.
> Update crawler details

- .github/workflows/main.yml
- package.json
- yarn.lock
To resolve critical issues and to update the workflow this update includes the following:
- Update workflow and actions to use node 16
- Update docusaurus to the latest version
- Add resolutions for some packages to ensure they are not using older versions with vulnerabilities
> Resolve critical issues

- .github/workflows/main.yml
Fix node version, so it's 16.20, not 16.2
> Fix node version

- package.json
- yarn.lock
Upgrade docusaurus-plugin-sass package to latest version to remove dependency to deprecated request library.
> Remove dependency to request library

- package.json
- yarn.lock
Remove rest of the obsolete request related dependencies.
> Remove obsolete request dependencies

- docs/playbook/ingesting-data/012-using-watermarks-to-record-job-states.md
adds description to the metadata, this is currently causing the deployment to fail
> add description
